export const SELECT_FRAME = "SELECT_FRAME";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const AUTHENTICATING_USER = "AUTHENTICATING_USER";
export const AUTHENTICATED_USER = "AUTHENTICATED_USER";
export const FAILED_LOGIN = "FAILED_LOGIN";
export const RESET = "RESET";