
// Users 
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const AUTHENTICATING_USER = "AUTHENTICATING_USER";
export const AUTHENTICATED_USER = "AUTHENTICATED_USER";
export const FAILED_LOGIN = "FAILED_LOGIN";
export const LOGOUT_USER = "LOGOUT_USER";


// Photos
export const PHOTO_CAPTURED = "PHOTO_CAPTURED";
export const PHOTO_ALL_CAPTURED = "PHOTO_ALL_CAPTURED";
export const RESET_PHOTOS = "RESET_PHOTOS";

// Frames
export const ADD_VERTICAL_FRAME = "ADD_VERTICAL_FRAME";
export const ADD_HORIZONTAL_FRAME = "ADD_HORIZONTAL_FRAME";
export const ADD_GIF_FRAME = "ADD_GIF_FRAME";
export const SELECT_FRAME = "SELECT_FRAME";

